-- Seed technologies
INSERT INTO technologies (name, category) VALUES
  ('Next.js', 'Frontend'),
  ('React', 'Frontend'),
  ('Vue.js', 'Frontend'),
  ('React Native', 'Mobile'),
  ('PostgreSQL', 'Database'),
  ('MongoDB', 'Database'),
  ('Node.js', 'Backend'),
  ('Express', 'Backend'),
  ('Socket.io', 'Backend'),
  ('Stripe', 'Payment'),
  ('Tailwind CSS', 'Styling'),
  ('Unity', 'Game Engine'),
  ('C#', 'Programming Language'),
  ('Chart.js', 'Visualization'),
  ('Weather API', 'API'),
  ('Geolocation', 'API'),
  ('Prisma', 'Database'),
  ('Markdown', 'Styling'),
  ('Redis', 'Database'),
  ('JWT', 'Security'),
  ('Docker', 'DevOps'),
  ('Sprite Animation', 'Game Engine');
