-- Seed technologies
INSERT INTO technologies (name, category) VALUES
  ('Next.js', 'Frontend'),
  ('React', 'Frontend'),
  ('Vue.js', 'Frontend'),
  ('Svelte', 'Frontend'),
  ('Angular', 'Frontend'),
  ('React Native', 'Mobile'),
  ('Flutter', 'Mobile'),
  ('Kotlin', 'Mobile'),
  ('Swift', 'Mobile'),
  ('PostgreSQL', 'Database'),
  ('MongoDB', 'Database'),
  ('MySQL', 'Database'),
  ('Redis', 'Database'),
  ('Cassandra', 'Database'),
  ('Node.js', 'Backend'),
  ('Express', 'Backend'),
  ('Nest.js', 'Backend'),
  ('Django', 'Backend'),
  ('Flask', 'Backend'),
  ('Socket.io', 'Backend'),
  ('GraphQL', 'Backend'),
  ('Stripe', 'Payment'),
  ('PayPal', 'Payment'),
  ('Braintree', 'Payment'),
  ('Tailwind CSS', 'Styling'),
  ('SASS', 'Styling'),
  ('CSS Modules', 'Styling'),
  ('Unity', 'Game Engine'),
  ('Unreal Engine', 'Game Engine'),
  ('Godot', 'Game Engine'),
  ('C#', 'Programming Language'),
  ('Python', 'Programming Language'),
  ('Rust', 'Programming Language'),
  ('Go', 'Programming Language'),
  ('TypeScript', 'Programming Language'),
  ('Chart.js', 'Visualization'),
  ('D3.js', 'Visualization'),
  ('Plotly', 'Visualization'),
  ('Weather API', 'API'),
  ('Geolocation', 'API'),
  ('OpenAI', 'API'),
  ('Google Maps', 'API'),
  ('Prisma', 'Database ORM'),
  ('Markdown', 'Styling'),
  ('JWT', 'Security'),
  ('OAuth', 'Security'),
  ('Docker', 'DevOps'),
  ('Kubernetes', 'DevOps'),
  ('Terraform', 'DevOps');